openapi: 3.0.0
info:
  title: Patient
  version: '1.0'
  description: 'Patients! '
servers:
  - url: 'http://localhost:3000'
paths:
  '/patient/{patientId}':
    parameters:
      - schema:
          type: string
        name: patientId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/patient'
      operationId: get-patient-patientId
      security:
        - API Key - 1: []
      description: ''
components:
  schemas:
    patient:
      title: patient
      type: object
      properties:
        identifier:
          type: object
          properties:
            use:
              type: string
            system:
              type: string
            value:
              type: string
            assigner:
              type: string
            type:
              type: string
        id:
          type: string
        '':
          type: string
  securitySchemes:
    API Key - 1:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
      description: ''
